### ISSUE TITLE
creating of db users and cheking of rights for each person 

### ISSUE THREAD

**Issue by jgrewe** [bendalab/animal_keeping#5]
I see two ways here:

1. The application, based on some information stored in the database, can handle rights.
2. The database handles this.

**Comment by DennisHub** [comment]
We agreed on doing this via the database, right?

**Comment by jgrewe** [comment]
Yes, the question is only how exactly. Maybe we should go the full way and implement a view that lets us define [privileges](https://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html) on the table level. We probably do not need all :)
Maybe we can define say three different standard roles for persons

**Comment by DennisHub** [comment]
Two roles should suffice, I think. One for Admin purposes with all rights, and one user role which can insert/update/delete/select/?
Not sure what an intermediate role would be.

**Comment by jgrewe** [comment]
The one with the delete and update right is something special, imho. The ordinary user should only be able to create and select. Corrections/edits, i.e. updates on existing entries should be restricted. I guess, there should only be very few admins who can do everything, and maybe a hand-full of people who can change existing things.

**Comment by DennisHub** [comment]
Ok, I   assumend that all the people   who look at the    database might want to add entries. This way it makes sense.

**Comment by jgrewe** [comment]
solved via pr #21
