### ISSUE TITLE
Subject Info Tab can be closed

### ISSUE THREAD

**Issue by gregorschulte-uni** [bendalab/animal_keeping#80]
I did not find a way to open it again (except restarting the app).
![image](https://user-images.githubusercontent.com/29063878/35285367-7b2cac0a-005d-11e8-8ee3-90e8983a9ff7.png)

**Comment by gregorschulte-uni** [comment]
Same for "Treatment type Information" and "License Info". 
And Inventory --> "Population Chart" and "Current Population"

**Comment by jgrewe** [comment]
closed via #87
